# Legacy parameters for deprecated polis pipeline
# polis_id: r2xcn2cdbmrzjmmuuytdk # American Assembly Bowling Green 2018
# polis_id: r7cwmiaxczyj8te9rzdmx # DemDis EU isolation

# PCA Subpipeline Parameters
pca:
  n_components: 2
  flip_x: true
  flip_y: false
